"liftovermap": '.\examples\CDS_500_2_502_liftover.csv'
"submission_spreadsheet": 'C:\Users\pihltd\Documents\modeltest\liftover\CDS_HTAN_imaging_v24.8.1_combined_20240905.xlsx'
"submission_worksheet": 'CDS_HTAN_imaging_v24.8.1_combin'
"output_directory": 'C:\Users\pihltd\Documents\modeltest\liftover\'
"target_model":
  - "https://raw.githubusercontent.com/CBIIT/cds-model/refs/heads/main/model-desc/cds-model.yml"
  - "https://raw.githubusercontent.com/CBIIT/cds-model/refs/heads/main/model-desc/cds-model-props.yml"
#Manual mapping is represented as old:new
"manual":
  "de-identification_method_type": "de_identification_method_type"
  "de-identification_method_description": "de_identification_method_description"
  "de-identification_software": "de_identification_software"
  "treatment_outcome": "response"
  "file_format": "file_type"
  "imaging_modality": "image_modality"
"required_columns":
  "participant": 
    - "study_participant_id" #Done dbgap+participant_id
  "study":
    - "study_diagnosis_id"  #phs, particpant_id, site_of_resection_or_biopsy
  "file":
    - "file_id" #Done file name, size, mdd5sum
  "image":
    - "study_link_id" #Done file name, size, md5sum
  "MultiplexMicroscopy":
    - "MultiplexMicroscopy_id" #Done file name, size, mdd5sum
  "NonDICOMpathologyImages":
    - "NonDICOMpathologyImages_id" #Done file name, size, mdd5sum
"keyrules":
  "study_participant_id":
    - "phs_accession"
    - "participant_id"
  "study_diagnosis_id":
    - "phs_accession"
    - "participant_id"
    - "site_of_resection_or_biopsy"
  "file_id":
    - "file_name"
    - "file_size"
    - "md5sum"
  "study_link_id":
    - "file_name"
    - "file_size"
    - "md5sum"
  "MultiplexMicroscopy_id":
    - "file_name"
    - "file_size"
    - "md5sum"
  "NonDICOMpathologyImages_id":
    - "file_name"
    - "file_size"
    - "md5sum"

#"transforms":
#  "study_diagnosis_id":
#    - "participant": "study_participant_id"
#    - "diagnosis_id"
#    - "study_diagnosis_id"
#  "study_link_id":
#    - "file_id"
#  "MultiplexMicroscopy_id":
#  - "study_link_id"
#  "study_participant_id":
#    - "study": "phs_accession"
#    - "participant": "participant_id"
#  "treatement_id":
#    - "participant": "participant_id"
#    - "therapy": "therapeutic_agent"
"relationship_columns":
  "diagnosis":
    - participant.study_participant_id
  "file":
    - "study.phs_accession"
    - "participant.study_participant_id"
    - "sample.sample_id"
  "genomic_info":
    - "file.file_id"
  "image":
    - "file.file_id"
  "MultiplexMicroscopy_id":
    - "image.study_link_id"
  "NonDICOMCTimages":
    - "image.study_link_id"
  "NonDICOMMRimages":
    - "image.study_link_id"
  "NonDICOMpathologyImages":
   - "image.study_link_id"
  "NonDICOMPETimages":
    - "image.study_link_id"
  "NonDICOMradiologyAllModalities":
    - "image.study_link_id"
  "participant":
    - "study.phs_accession"
  "proteomic":
    - "file.file_id"
  "sample":
    - "participant.study_participant_id"
  "study":
    - "program.program_acronym"
  "treatment":
    - "participant.study_participant_id"
  
  
  