"liftovermap": '.\examples\TEST_CDS_500_2_504_liftover.csv'
"submission_spreadsheet": 'C:\Users\pihltd\Documents\modeltest\liftover\CDS_HTAN_imaging_v24.8.1_combined_20240905.xlsx'
"submission_worksheet": 'CDS_HTAN_imaging_v24.8.1_combin'
"output_directory": 'C:\Users\pihltd\Documents\modeltest\liftover\'
"target_model":
  - "https://raw.githubusercontent.com/CBIIT/cds-model/refs/heads/main/model-desc/cds-model.yml"
  - "https://raw.githubusercontent.com/CBIIT/cds-model/refs/heads/main/model-desc/cds-model-props.yml"
#Manual mapping is represented as old:new
"manual":
  "de-identification_method_type": "de_identification_method_type"
  "de-identification_method_description": "de_identification_method_description"
  "de-identification_software": "de_identification_software"
  "treatment_outcome": "response"
  "file_format": "file_type"
  "imaging_modality": "image_modality"
  "proteomic_info_id": "proteomic_info_id"
# The keyrules are an attempt to make a machine actionable list of what to do with key fields.
# If compound is No, a UUID will be generated.
# If compound is Yes, the fields in method will be concatenated
# If compound is Exempt, use the submitter provided values.
# There are some instances where a field is not key, but is used in the keyrules.  Add them here as node:field
"manual_key":
  "diagnosis":
    - "diagnosis_id"
"keyrules":
  "diagnosis_id":
    "compound": "No"
  "study_participant_id":
    "compound": "Yes"
    "method":
      - "phs_accession"
      - "participant_id"
  "study_diagnosis_id":
    "compound": "Yes"
    "method":
      - "diagnosis_id"
      - "phs_accession"
      - "participant_id"
  "file_id":
    "compound": "No"
  "study_link_id":
    "compound": "No"
  "treatment_id":
    "compound": "Yes"
    "method":
    - "phs_accession"
    - "participant_id"
    - "therapeutic_agents"
  "genomic_info_id":
    "compound": "Yes"
    "method":
      - "file_id"
      - "library_id"
  "MultiplexMicroscopy_id":
    "compound": "No"
  "NonDICOMMRimages_id":
    "compound": "No"
  "NonDICOMCTimages_id":
    "compound": "No"
  "NonDICOMPETimages_id":
    "compound": "No"
  "NonDICOMradiologyAllModalities_id":
    "compound": "No"
  "NonDICOMpathologyImages_id":
    "compound": "No"
    "method":
      - "file_name"
      - "file_size"
      - "md5sum"
      - "tumor_tissue_type"
  "proteomic_info_id":
    "compound": "No"
  "data_version_id":
    "compound": "No"
  "phs_accession":
    "compound": "Exempt"
  "sample_id":
    "compound": "No"
  "program_acronym":
    "compound": "Exempt"
  
  
  