"old_version_files":
  - "https://raw.githubusercontent.com/CBIIT/cds-model/refs/heads/5.0.0/model-desc/cds-model.yml"
  - "https://raw.githubusercontent.com/CBIIT/cds-model/refs/heads/5.0.0/model-desc/cds-model-props.yml"
"new_version_files":
  - "https://raw.githubusercontent.com/CBIIT/cds-model/refs/heads/5.0.4/model-desc/cds-model.yml"
  - "https://raw.githubusercontent.com/CBIIT/cds-model/refs/heads/5.0.4/model-desc/cds-model-props.yml"
"mapping_file": '.\examples\TEST_CDS_500_2_504_liftover.csv'
"old_df": '.\examples\TEST_old_df_info.csv'
"new_df": '.\examples\TEST_new_df_info.csv'